# Use this file in conjunction with supervised.yaml
model:
  init_args:
    net:
      init_args:
        module:
          init_args:
            output_size: 24 # 6 + 14 + 4 options for the three slots
    criterion:
      class_path: torch_mate.loss.SegmentedCrossEntropyLoss
      init_args:
        segments: [6, 14, 4]
    metrics:
      accuracy:
        class_path: torch_mate.utils.segmented_accuracy.SegmentedAccuracy
        init_args:
          segments: [6, 14, 4]
data:
  init_args:
    per_slot_targets: true